name: Check dist

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  verify-build: # make sure the checked in dist/ folder matches the output of a rebuild
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install NPM dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: npm run build

      - name: Compare the expected and actual dist/ directories
        run: bin/check-diff
